main: de.timesnake.extension.event.main.ExEvent
version: 1.2.2
name: extension-event
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.13

commands:
  easter:
  birthday:
  christmas:
  april:
