main: de.timesnake.extension.event.main.ExEvent
version: ${version}
name: extension-event
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.21

commands:
  easter:
  birthday:
  christmas:
  april:
